import unittest
from test_func import TestFunc
from HTMLTestReportCN import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    # 测试第二次提交

    tests = [TestFunc("test_add"), TestFunc("test_minus"), TestFunc("test_divide")] # 添加测试用例列表
    suite.addTests(tests) # 将测试用例列表添加到测试组中
    suite.addTest(TestFunc("test_multi")) # 直接用addTest方法添加单个TestCase
    # 用addTests + TestLoader。不过用TestLoader的方法是无法对case进行排序的
    # loadTestsFromName()，传入模块名.TestCase名
    suite.addTests(unittest.TestLoader().loadTestsFromName('test_func.TestFunc'))
    suite.addTests(unittest.TestLoader().loadTestsFromNames(['test_func.TestFunc'])) # loadTestsFromNames(),类似，传入参数

    # loadTestsFromTestCase(),传入TestCase
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestFunc))

    # suite中也可以套suite

    # 将测试结果输出到测试报告中
    # with open('UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    # 将测试结果输出到测试报告html中
    with open('HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Func Test Report',
                                description='generated by HTMLTestRunner',
                                verbosity=3,
                                tester='xuanlh'
                                )
        runner.run(suite)

    # 直接将报告输出到控制台
    # runner = unittest.TextTestRunner(verbosity=2)
    # runner.run(suite)